# Generated by Django 5.0.7 on 2024-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='batch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='logo',
            field=models.ImageField(upload_to='startups/logos/'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='startup',
            name='tags',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='startup',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
