# Generated by Django 5.0.7 on 2024-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_alter_startup_batch_alter_startup_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
