# Generated by Django 5.0.7 on 2024-08-04 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('welcome_text', models.TextField()),
                ('footer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StartupBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('startup_name', models.CharField(max_length=200)),
                ('startup_description', models.TextField()),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to='startups/')),
                ('tags', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.landingpage')),
            ],
        ),
    ]
