# Generated by Django 5.0.7 on 2024-08-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('welcome_text', models.TextField()),
                ('section_text', models.TextField()),
                ('footer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('welcome_text', models.TextField()),
                ('section_text', models.TextField()),
                ('footer_text', models.TextField()),
                ('startup_batches', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='landing_page',
        ),
        migrations.DeleteModel(
            name='StartupBatch',
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
